# Generated by Django 5.2.8 on 2025-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_partner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
